apiVersion: v1
kind: Service
metadata:
  name: kogito-data-index
  namespace: business-automation
spec:
  selector:
    app: kogito-data-index
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP