apiVersion: v1
kind: ConfigMap
metadata:
  name: jobs-service-config
  namespace: business-automation
data:
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgresql.data.svc.cluster.local:5432/kogito
  QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://postgresql.data.svc.cluster.local:5432/kogito
  QUARKUS_DATASOURCE_DB_KIND: postgresql
  QUARKUS_FLYWAY_MIGRATE_AT_START: "true"