apiVersion: v1
kind: Secret
metadata:
  name: jobs-service-secret
  namespace: business-automation
type: Opaque
stringData:
  QUARKUS_DATASOURCE_USERNAME: kogito
  QUARKUS_DATASOURCE_PASSWORD: kogito123